In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,Hilo,90,US,2021-03-21 17:42:05,83,19.7297,-155.0900,68.00,5.75
1,1,Tuatapere,84,NZ,2021-03-21 17:42:13,95,-46.1333,167.6833,53.01,4.00
2,2,Provideniya,100,RU,2021-03-21 17:42:13,80,64.3833,-173.3000,3.97,1.88
3,3,Gasa,99,PS,2021-03-21 17:43:51,54,31.5000,34.4667,75.00,5.37
4,4,Arraial Do Cabo,20,BR,2021-03-21 17:42:11,70,-22.9661,-42.0278,84.20,21.85

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Cloudiness      int64
Country        object
Date           object
Humidity        int64
Lat           float64
Lng           float64
Max Temp      float64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)
gmaps

In [5]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])

In [6]:
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
3,3,Gasa,99,PS,2021-03-21 17:43:51,54,31.5000,34.4667,75.00,5.37
4,4,Arraial Do Cabo,20,BR,2021-03-21 17:42:11,70,-22.9661,-42.0278,84.20,21.85
12,12,Rikitea,38,PF,2021-03-21 17:42:15,74,-23.1203,-134.9692,79.77,8.57
16,16,Atuona,9,PF,2021-03-21 17:42:06,77,-9.8000,-139.0333,80.17,15.14
19,19,Cidreira,100,BR,2021-03-21 17:42:47,84,-30.1811,-50.2056,77.20,8.99
31,31,Bambanglipuro,91,ID,2021-03-21 17:44:00,85,-7.9500,110.2833,77.74,3.20
42,42,Castro,82,BR,2021-03-21 17:42:17,81,-24.7911,-50.0119,76.14,5.12
44,44,Saint-Pierre,90,RE,2021-03-21 17:47:13,83,-21.3393,55.4781,78.80,18.41
46,46,Tuni,42,IN,2021-03-21 17:47:18,77,17.3500,82.5500,75.83,1.68
48,48,Vaini,40,TO,2021-03-21 17:42:17,94,-21.2000,-175.2000,75.20,3.44

In [12]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
3,3,Gasa,99,PS,2021-03-21 17:43:51,54,31.5000,34.4667,75.00,5.37
4,4,Arraial Do Cabo,20,BR,2021-03-21 17:42:11,70,-22.9661,-42.0278,84.20,21.85
12,12,Rikitea,38,PF,2021-03-21 17:42:15,74,-23.1203,-134.9692,79.77,8.57
16,16,Atuona,9,PF,2021-03-21 17:42:06,77,-9.8000,-139.0333,80.17,15.14
19,19,Cidreira,100,BR,2021-03-21 17:42:47,84,-30.1811,-50.2056,77.20,8.99
31,31,Bambanglipuro,91,ID,2021-03-21 17:44:00,85,-7.9500,110.2833,77.74,3.20
42,42,Castro,82,BR,2021-03-21 17:42:17,81,-24.7911,-50.0119,76.14,5.12
44,44,Saint-Pierre,90,RE,2021-03-21 17:47:13,83,-21.3393,55.4781,78.80,18.41
46,46,Tuni,42,IN,2021-03-21 17:47:18,77,17.3500,82.5500,75.83,1.68
48,48,Vaini,40,TO,2021-03-21 17:42:17,94,-21.2000,-175.2000,75.20,3.44

In [13]:
preferred_cities_df.count()

City_ID       181
City          181
Cloudiness    181
Country       180
Date          181
Humidity      181
Lat           181
Lng           181
Max Temp      181
Wind Speed    181
dtype: int64

In [14]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

               City Country  Max Temp      Lat       Lng Hotel Name
3              Gasa      PS     75.00  31.5000   34.4667
4   Arraial Do Cabo      BR     84.20 -22.9661  -42.0278
12          Rikitea      PF     79.77 -23.1203 -134.9692
16           Atuona      PF     80.17  -9.8000 -139.0333
19         Cidreira      BR     77.20 -30.1811  -50.2056
31    Bambanglipuro      ID     77.74  -7.9500  110.2833
42           Castro      BR     76.14 -24.7911  -50.0119
44     Saint-Pierre      RE     78.80 -21.3393   55.4781
46             Tuni      IN     75.83  17.3500   82.5500
48            Vaini      TO     75.20 -21.2000 -175.2000

In [15]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
# Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [16]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
3,Gasa,PS,75.00,31.5000,34.4667,رابطة الفنانين الفلسطينيين
4,Arraial Do Cabo,BR,84.20,-22.9661,-42.0278,Pousada Porto Praia
12,Rikitea,PF,79.77,-23.1203,-134.9692,Pension Maro'i
16,Atuona,PF,80.17,-9.8000,-139.0333,Villa Enata
19,Cidreira,BR,77.20,-30.1811,-50.2056,Hotel Castelo
...,...,...,...,...,...,...
545,Santa Isabel,BR,86.00,-23.3156,-46.2214,Chácara Sombra do Altíssimo
546,Ternate,ID,81.07,0.8000,127.4000,Grand Dafam Bela Ternate
547,Texistepec,MX,75.20,17.8833,-94.7833,AMPLIACIÓN MIGUEL ALEMÁN 2
550,Pemangkat,ID,77.88,1.1667,108.9667,Kost H.Syamsuddin
553,Pontes E Lacerda,BR,82.78,-15.2261,-59.3353,Hotel Bressan

In [17]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [20]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))